import type { Metadata } from "next";
import { Cairo_Play, Cairo } from "next/font/google";
import "./globals.css";
import ParticlesComponent from "@/components/ui/Particles";
import { ThemeProvider } from "@/providers/theme-provider";
import { LanguageProvider } from "@/providers/LanguageContextProvider";

const FontCairoPlay = Cairo_Play({
  variable: "--FontCairoPlay",
  subsets: ["latin"],
});

const FontCairo = Cairo({
  variable: "--FontCairo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Elmadany",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${FontCairo.variable} ${FontCairoPlay.variable} antialiased`}
      >
        <ParticlesComponent />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LanguageProvider>
            {children}
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
